Use LazyVim

diff --git a/init b/init
--- a/init
+++ b/init
@@ -20,55 +20,55 @@ Cyan='\033[46m'
 White='\033[47m'
 
 prerequisites=(
-    "git"
-    "curl"
-    "wget"
-    "zsh"
-    "tmux"
+  "git"
+  "curl"
+  "wget"
+  "zsh"
+  "tmux"
 )
 
 Prerequisite_Dir="./prerequisite"
 
 echo -e "${YELLOW}Checking prerequisites...${NC}"
 for item in ${prerequisites[@]}; do
-    if ! command -v "${item}" > /dev/null 2>&1; then
-        echo -en "${RED}Doesn't find "${item}". Install now?${NC} [${UNDERLINE}Y${NC}/n] "
-        read -r install
-        if [ -z ${install} ]; then
-            install="Y"
-        fi
-        if [ ${install} == "Y" ]; then
-            Script="${Prerequisite_Dir}"/"${item}".install
-            . ${Script}
-        else
-            echo -e "${RED}Initialization failed${NC}"
-            exit 1
-        fi
+  if ! command -v "${item}" >/dev/null 2>&1; then
+    echo -en "${RED}Doesn't find "${item}". Install now?${NC} [${UNDERLINE}Y${NC}/n] "
+    read -r install
+    if [ -z ${install} ]; then
+      install="Y"
     fi
+    if [ ${install} == "Y" ]; then
+      Script="${Prerequisite_Dir}"/"${item}".install
+      . ${Script}
+    else
+      echo -e "${RED}Initialization failed${NC}"
+      exit 1
+    fi
+  fi
 done
-echo -e "${GREEN}All prerequisites have been met${NC}" 
+echo -e "${GREEN}All prerequisites have been met${NC}"
 
 # Setup SSH key to Github
 echo -en "Do you want to generate ssh-key to github now?[${BOLD}${UNDERLINE}Y${NC}/n]:"
 read -r github_ssh
 if [ -z ${github_ssh} ]; then
-    github_ssh="Y"
+  github_ssh="Y"
 fi
 if [ ${github_ssh} = "Y" ]; then
-    if [ -f ${HOME}/.ssh/id_ed25519 ]; then
-        echo -e "${YELLOW}Key already exists.${NC}"
-    else
-        echo -en "Your email: (To connect to Github using ssh):"
-        read Email
-        ssh-keygen -t ed25519 -C ${Email}
-    fi
-    echo -e "${GREEN}The public key is:${NC}"
-    cat ${HOME}/.ssh/id_ed25519.pub
+  if [ -f ${HOME}/.ssh/id_ed25519 ]; then
+    echo -e "${YELLOW}Key already exists.${NC}"
+  else
+    echo -en "Your email: (To connect to Github using ssh):"
+    read Email
+    ssh-keygen -t ed25519 -C ${Email}
+  fi
+  echo -e "${GREEN}The public key is:${NC}"
+  cat ${HOME}/.ssh/id_ed25519.pub
 fi
 
 # Get Oh-my-zsh
 if ! [ -d ${HOME}/.oh-my-zsh ]; then
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
 fi
 
 # Get zsh plugins
@@ -76,7 +76,7 @@ echo -e "${YELLOW}Getting oh-my-zsh plugins...${NC}"
 . plugins.zsh
 
 # Configure LazyVim
-git clone -b 01-options https://github.com/LunarVim/Neovim-from-scratch.git ~/.config/nvim
+git clone https://github.com/LazyVim/LazyVim ${HOME}/.config/nvim
 
 # Execute the sync script
 echo -e "${BLUE}Synchronizing config files...${NC}"
@@ -87,4 +87,3 @@ echo -e "${BLUE}Synchronizing config files...${NC}"
 
 echo -e "All Done!"
 echo -e "Reconnect to terminal then type ${GREEN}source \${HOME}/.zshrc${NC} to work with a brand new shell!"
-
